server:
  port: 8080

spring:
  application:
    name: webhook-outbox
  datasource:
    url: jdbc:postgresql://localhost:5432/webhooks
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

webhook:
  hmac-secret: secret
  max-attempts: 10
  backoff:
    base-ms: 1000
    factor: 2.0
    max-ms: 300000
    jitter-percent: 10
